export const southAfricaSearch = [
  {
    name: "SouthAfrica",
    subCategories: [""]
  },
  {
    name: "Eastern Cape",
    subCategories: [
      "Alice",
      "Butterworth",
      "East London",
      "Graaff-Reinet",
      "Grahamstown",
      "King Williams Town",
      "Mthatha",
      "Port Elizabeth",
      "Queenstown",
      "Uitenhage",
      "Zwelitsha",
    ],
  },
  {
    name: "Free State",
    subCategories: [
      "Bethlehem",
      "Bloemfontein",
      "Jagersfontein",
      "Kroonstad",
      "Odendaalsrus",
      "Parys",
      "Phuthaditjhaba",
      "Sasolburg",
      "Virginia",
      "Welkom",
    ],
  },
  {
    name: "Gauteng",
    subCategories: [
      "Benoni",
      "Boksburg",
      "Brakpan",
      "Carletonville",
      "Germiston",
      "Johannesburg",
      "Krugersdorp",
      "Pretoria",
      "Randburg",
      "Randfontein",
      "Roodepoort",
      "Soweto",
      "Springs",
      "Vanderbijlpark",
      "Vereeniging",
    ],
  },
  {
    name: "KwaZulu-Natal",
    subCategories: [
      "Durban",
      "Empangeni",
      "Ladysmith",
      "Newcastle",
      "Pietermaritzburg",
      "Pinetown",
      "Ulundi",
      "Umlazi",
    ],
  },
  {
    name: "Limpopo",
    subCategories: [
      "Giyani",
      "Lebowakgomo",
      "Musina",
      "Phalaborwa",
      "Polokwane",
      "Seshego",
      "Sibasa",
      "Thabazimbi",
    ],
  },
  {
    name: "Mpumalanga",
    subCategories: ["Emalahleni", "Nelspruit", "Secunda"],
  },
  {
    name: "North West",
    subCategories: [
      "Klerksdorp",
      "Mahikeng",
      "Mmabatho",
      "Potchefstroom",
      "Rustenburg",
    ],
  },
  {
    name: "Northern Cape",
    subCategories: ["Kimberley", "Kuruman", "Port Nolloth"],
  },
  {
    name: "Western Cape",
    subCategories: [
      "Bellville",
      "Cape Town",
      "Constantia",
      "George",
      "Hopefield",
      "Oudtshoorn",
      "Paarl",
      "Simons Town",
      "Stellenbosch",
      "Swellendam",
      "Worcester",
    ],
  },
]
