CREATE TABLE `listingProperty` (
  `id` varchar(191) NOT NULL,
  `authorId` varchar(191) NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp DEFAULT CURRENT_TIMESTAMP,
  `expirationDate` datetime,
  `purgeDate` datetime,
  `category` varchar(191),
  `price` int,
  `title` varchar(191),
  `description` text,
  `bedroom` varchar(191),
  `bathroom` varchar(191),
  `garage` varchar(191),
  `parkingSpace` varchar(191),
  `internet` varchar(191),
  `petFriendly` boolean DEFAULT false,
  `availableStart` datetime,
  `availableEnd` datetime,
  `images` text,
  `location` varchar(191),
  `isAvailable` boolean NOT NULL DEFAULT true,
  CONSTRAINT `listingProperty_id` PRIMARY KEY(`id`),
  CONSTRAINT `listingProperty__id__idx` UNIQUE(`id`)
);