export const categoryFarmingAgriculture = [
  {
    name: "Tractors & Heavy Machinery",
    subCategories: [
      "Tractors (Compact, Utility, Row-Crop)",
      "Harvesters (Combine, Forage, Cotton)",
      "Plows (Moldboard, Chisel, Disc)",
      "Cultivators (Field, Garden, Rotary)",
      "Tractor Attachments (Loaders, Mowers, Forks)",
      "Sprayers (Boom, Mist, Backpack)",
      "Seeders & Planters (Drills, Air Seeders, Precision Planters)",
      "Balers (Round, Square)",
      "Farm Trailers & Wagons",
    ],
  },
  {
    name: "Livestock & Poultry",
    subCategories: [
      "Cattle (Dairy, Beef, Calves)",
      "Sheep & Goats (Wool, Meat, Dairy)",
      "Pigs (Piglets, Sows, Boars)",
      "Chickens (Layers, Broilers, Chicks)",
      "Ducks, Turkeys & Other Poultry",
      "Horses (Work, Riding, Breeding)",
      "Livestock Feeders & Waterers",
      "Animal Fencing (Electric, Portable, Netting)",
      "Livestock Trailers",
    ],
  },
  {
    name: "Farming Tools & Equipment",
    subCategories: [
      "Hand Tools (Shovels, Hoes, Rakes)",
      "Power Tools (Chainsaws, Hedge Trimmers)",
      "Irrigation Systems (Drip, Sprinkler, Pivot)",
      "Fencing & Supplies (Posts, Wire, Gates)",
      "Grain Handling Equipment (Conveyors, Grain Bins)",
      "Crop Protection (Pesticides, Herbicides, Fertilizers)",
      "Greenhouse & Nursery Supplies",
      "Soil Preparation Tools (Tillers, Harrows, Rotary Hoes)",
    ],
  },
  {
    name: "Seeds, Plants & Trees",
    subCategories: [
      "Vegetable Seeds (Tomatoes, Corn, Lettuce)",
      "Fruit Trees & Plants (Apple, Orange, Berries)",
      "Flowers & Ornamental Plants (Roses, Tulips, Shrubs)",
      "Grains & Cereals (Wheat, Barley, Rice)",
      "Grass & Pasture Seeds (Alfalfa, Clover, Ryegrass)",
      "Forestry Trees (Pine, Oak, Eucalyptus)",
      "Cover Crops (Legumes, Grasses)",
      "Seedlings & Saplings",
    ],
  },
  {
    name: "Animal Feed & Supplies",
    subCategories: [
      "Livestock Feed (Hay, Silage, Grain Mixes)",
      "Poultry Feed (Layers, Growers, Starters)",
      "Horse Feed (Pellets, Oats, Sweet Feed)",
      "Animal Health Products (Vaccines, Supplements, Dewormers)",
      "Feed Storage Solutions (Bins, Silos, Bags)",
      "Automatic Feeders & Waterers",
      "Mineral Supplements & Salt Blocks",
      "Animal Bedding (Straw, Shavings, Mats)",
    ],
  },
  {
    name: "Farming Infrastructure & Structures",
    subCategories: [
      "Barns & Sheds (Prefab, Metal, Wood)",
      "Greenhouses & Nurseries (Polytunnels, Shade Cloth)",
      "Fencing Solutions (Wood, Electric, Mesh)",
      "Water Tanks & Troughs",
      "Solar Panels & Energy Solutions",
      "Livestock Shelters (Chicken Coops, Pig Pens, Horse Stables)",
      "Farm Gates & Corrals",
      "Grain Silos & Storage",
    ],
  },
  {
    name: "Agricultural Technology & Innovations",
    subCategories: [
      "GPS & Precision Farming (Drones, Auto-Steering Systems)",
      "Smart Irrigation Systems",
      "Farm Management Software",
      "Weather Monitoring & Sensors",
      "Automated Feeding Systems",
      "Electric Fencing & Monitoring Systems",
      "Solar Powered Farm Equipment",
      "Livestock Tracking & Identification",
    ],
  },
  {
    name: "Organic Farming & Sustainable Practices",
    subCategories: [
      "Organic Seeds & Plants",
      "Composting Equipment",
      "Biodegradable Mulch & Covers",
      "Pest Control (Natural, Biological, Organic Solutions)",
      "Soil Enhancers (Compost, Manure, Mulch)",
      "Water Conservation Tools",
      "Cover Crops & Crop Rotation Tools",
      "Sustainable Farming Books & Resources",
    ],
  },
]
