export const categoryFashion = [
  {
    name: "Mens Clothing",
    subCategories: [
      "Shirts",
      "Golfers",
      "Pants",
      "Shorts",
      "Denim Jeans",
      "Jackets & Hoodies",
      "Activewear",
      "Swimwear",
      "Shoes",
      "Accessories",
    ],
  },
  {
    name: "Womens Clothing",
    subCategories: [
      "Tops",
      "Shirts",
      "Pants",
      "Denim Jeans",
      "Shorts & Jorts",
      "Skirts",
      "Dresses",
      "Jackets & Hoodies",
      "Leggings",
      "Sleepwear",
      "Activewear",
      "Swimwear",
      "Shoes",
      "Accessories",
    ],
  },
  {
    name: "Boys Clothing",
    subCategories: [
      "Shirts",
      "Golfers",
      "Pants",
      "Shorts",
      "Denim Jeans",
      "Jackets & Hoodies",
      "Activewear",
      "Sleepwear",
      "Swimwear",
      "Shoes",
      "Accessories",
    ],
  },
  {
    name: "Girls Clothing",
    subCategories: [
      "Tops",
      "Shirts",
      "Pants",
      "Denim Jeans",
      "Shorts & Jorts",
      "Skirts",
      "Dresses",
      "Jackets & Hoodies",
      "Leggings",
      "Sleepwear",
      "Activewear",
      "Swimwear",
      "Shoes",
      "Accessories",
    ],
  },
  {
    name: "Baby Clothing",
    subCategories: [
      "Onesies & Babygrows",
      "Tops & T-Shirts",
      "Pants & Jeans",
      "Shorts",
      "Dresses & Skirts",
      "Jackets & Hoodies",
      "Tracksuits",
      "Sleepwear",
      "Swimwear",
      "Bibs & Burp Cloths",
      "Blankets & Swaddles",
      "Shoes",
      "Accessories",
    ],
  },
]
