export const categorySportsOutdoors = [
  {
    name: "Sports Equipment",
    subCategories: [
      "Basketball",
      "Cycling",
      "Cricket",
      "Golfing",
      "Hockey",
      "Netball",
      "Rugby",
      "Soccer",
      "Swimming",
      "Tennis & Squash",
      "Triathlon",
      "Volleyball",
      "Water Polo",
      "Other sports",
    ],
  },
  {
    name: "Extreme Sports Equipment",
    subCategories: [
      "Motocross & Enduro",
      "Motor Racing",
      "BMX Biking",
      "Skateboarding",
      "Rollerblading",
      "Surfing",
      "Wakeboarding",
      "Kayaking",
      "Climbing & Hiking",
      "Skydiving & BASE Jumping",
      "Aviation & Aeronatics",
      "Skiing & Snowboarding",
      "Other Extreme Sports",
    ],
  },
  {
    name: "Fitness Gear",
    subCategories: [
      "Weightlifting Equipment",
      "Cardio Equipment",
      "Combat Sports Equipment",
      "Massage & Recovery",
      "Fitness Apparel",
      "Home Gyming Accessories",
    ],
  },
  {
    name: "Camping & Outdoors",
    subCategories: [
      "Tents & Sheltering",
      "Camping Furniture",
      "Outdoor Culinary",
      "Lighting & Gadgets",
      "Camping Accessories",
      "Fishing",
      "Hiking",
      "Hunting",
    ],
  },
]
